object:
  mesh_path: "resources/balloon.stl"
  roh: 1. # 1.17 g/cm^3
octree:
  init_resolution: 2
  max_resolution_levels: 3
loss:
  phi: 0
  calc_type: "top" # "yoyo"
  gamma_i: 0.9
  gamma_c: 0.7
optimizer:
  # name: Adam
  # args:
  #   lr: 1e-3
  name: "nlopt"
  args:
    algorithm: "LN_COBYLA"