mesh_path: "resources/Orangutan-man_mini_figures_1.stl"
octree:
  init_resolution: 10
  max_resolution_levels: 2
  roh: 1. # 1.17 g/cm^3
optimizer:
  calc_type: "top" # "yoyo"
  gamma_l: 0.2
  gamma_i: 0.6
  gamma_c: 0.9