object:
  mesh_path: "resources/balloon.stl"
  roh: 1. # 1.17 g/cm^3
octree:
  init_resolution: 10
  max_resolution_levels: 2
optimizer:
  calc_type: "top" # "yoyo"
  gamma_l: 0.2
  gamma_i: 0.9
  gamma_c: 0.7