name: spinit
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python==3.10
  - pyyaml
  - trimesh
  - scipy
  - scikit-learn
  - scikit-image
  - pandas
  - igl
  - pytorch<=1.12.1
  - torchvision
  - cudatoolkit
  - nlopt
  - wandb
  - matplotlib